[tool.poetry]
name = "smsc-client"
version = "0.1.0"
description = ""
authors = ["nicos_backbase <nicos@backbase.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
smpplib = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
